spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sell_user
    password: 123456
    url: jdbc:mysql://115.159.206.60:3306/wechat_sell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

